#!/bin/bash
cd
if [ $(id -u) -eq 0 ]
then
clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root e fazer a instalação execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Vc pecisa esta como root para poder fazer a instalção, Para virar root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi
rm /bin/vercao
wget https://raw.githubusercontent.com/Nilbertocs/NNetPack/master/vercao -O /bin/vercao
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Este script irá:" ; echo ""
        echo "● Instalar e configurar o proxy squid nas portas 80, 3128, 8080 e 8799"
        echo "● Configurar o OpenSSH para rodar nas portas 22 e 443"
        echo "● Instalar e Configurar o OpenVPN"
        echo "● Instalar um conjunto de scripts como comandos do sistema para o gerenciamento" ; tput sgr0
        echo ""
tput setaf 3 ; tput bold ; read -n 1 -s -p "Aperte qualquer tecla para continuar..." ; echo "" ; echo "" ; tput sgr0
clear
IP=$(wget -qO- ipv4.icanhazip.com)
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ;      echo ""
tput setaf 3 ; tput bold ; read -p "Confirme o IP deste servidor: " -e -i $IP ipdovps tput sgr0
if [ -z "$ipdovps" ]
then
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ;      echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo " Você não digitou o IP deste servidor. Tente novamente. " ; echo "" ; echo "" ; tput sgr0
exit 1
fi
clear
#SSHUses
if [ -f "/root/usuarios.db" ]
then
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ;      echo ""
echo "Encontrei uma base de dados de usuários SSH!"
tput setaf 6 ; tput bold ;      echo ""
echo "[1] Manter Base Atual"
echo "[2] Recriar Base de Dados"
echo "" ; tput sgr0
read -p "Opção?: " -e -i 1 optiondb
else
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
clear
#OVPNUsers
if [ -f "/root/openclientes.db" ]
then
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ;      echo ""
echo "Encontrei uma base de dados de usuários OVPN!"
tput setaf 6 ; tput bold ;      echo ""
echo "[1] Manter Base Atual"
echo "[2] Recriar Base de Dados"
echo "" ; tput sgr0
read -p "Opção?: " -e -i 1 optiondb
else
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/openclientes.db
fi
#Compressão SSH 
echo ""
tput setaf 3 ; tput bold ; read -p "Ativar a compressão SSH (pode aumentar o consumo de RAM)? [s/n]) " -e -i n sshcompression tput sgr0
echo ""
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒00%▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Vamos começar atualizando o sistema e baixando algumas coisas..." ; tput sgr0
sleep 3
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒02%▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Atualizando Sistema..." ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Isso pode demorar um pouco" ; tput sgr0
apt-get update 1>/dev/null 2>/dev/null
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "████████████████████▒▒▒▒▒40%▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Instalando servidores e iniciando serviços..." ; tput sgr0
apt-get install squid3 bc screen nano unzip git dos2unix wget htop python-pip -y 1>/dev/null 2>/dev/null
pip install speedtest-cli
killall apache2
apt-get purge apache2 1>/dev/null 2>/dev/null
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████▒▒▒44%▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Baixando Pack de scripts para o controle..." ; tput sgr0
sleep 2
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████50%▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Baixando Pack de scripts para o controle..." ; tput sgr0
git clone https://github.com/Nilbertocs/NNetPack.git 1>/dev/null 2>/dev/null
sleep 1
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████56%███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Baixando Pack de scripts para o controle..." ; tput sgr0
cd NNetPack
sleep 2
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████62%██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Baixando Pack de scripts para o controle..." ; tput sgr0
rm -rf README.md
sleep 1
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████68%█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Baixando Pack de scripts para o controle..." ; tput sgr0
rm -rf install
sleep 1
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████74%████████████▒▒▒▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Instalando scripts..." ; tput sgr0
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
sleep 4
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████80%███████████████▒▒▒▒▒▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Criando regras no firewall..." ; tput sgr0
sleep 2
if [ -f "/usr/sbin/ufw" ] ; then
        ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
fi
clear
echo "# Portas do SQUID
http_port 80
http_port 8080
http_port 3128
# ACLs e Liberações
acl accept dstdomain -i $ipdovps
acl allowed dstdomain -i /etc/squid3/payloads
acl combr dstdomain -i .com.br
acl com dstdomain -i .com
#acl all src 0.0.0.0/0.0.0.0
http_access allow accept
http_access allow allowed
http_access allow combr
http_access allow com
http_access deny all
always_direct allow all
# Anonimo
forwarded_for off
# Pipeline
#pipeline_prefetch on
" > /etc/squid3/squid.conf
wget https://raw.githubusercontent.com/Nilbertocs/NNetPack/master/payload.text -O /etc/squid3/payload.txt
clear
echo " " >> /etc/squid3/payload.txt
echo -e "Port 443" >> /etc/ssh/sshd_config
echo "Banner /etc/banner" >> /etc/ssh/shhd_config
grep -v "^PasswordAuthentication yes" /etc/ssh/sshd_config > /tmp/passlogin && mv /tmp/passlogin /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████90%████████████████████▒▒▒▒▒" ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "Criando regras no firewall..." ; tput sgr0
sleep 2
#REINICIANDO SQUID E OPENSSH
squid3 -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid3 restart 1>/dev/null 2>/dev/null
clear
#FINALIZANDO CONFIGURAÇÃO SSH
if [[ "$optiondb" = '2' ]]; then
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > /root/usuarios.db
fi
if [[ "$sshcompression" = 's' ]]; then
grep -v "^Compression yes" /etc/ssh/sshd_config > /tmp/sshcp && mv /tmp/sshcp /etc/ssh/sshd_config
echo "Compression yes" >> /etc/ssh/sshd_config
fi
if [[ "$sshcompression" = 'n' ]]; then
grep -v "^Compression yes" /etc/ssh/sshd_config > /tmp/sshcp && mv /tmp/sshcp /etc/ssh/sshd_config
fi
cd
rm -rf install 2> /dev/null
rm -rf VpsPack 2> /dev/null
clear
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0
tput setaf 6 ; tput bold ; echo "" ; echo "█████████████████████████100%█████████████████████████" ; tput sgr0
echo ""
tput setaf 2 ; tput setab 1 ; tput bold ; echo "                          Tudo Pronto!!!                         " ; tput sgr0
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Proxy Squid Instalado e rodando nas portas: 80, 3128, 8080 e 8799" ; tput sgr0
tput setaf 7 ; tput setab 1 ; tput bold ; echo "OpenSSH rodando nas portas 22 e 443                              " ; tput sgr0
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Canal do telegram, para saber de atualizações @NilbertoNNet      " ; tput sgr0
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Para iniciar use o comando: menu                                 " ; tput sgr0
tput setaf 7 ; tput setab 1 ; tput bold ; echo "                                                                 " ; tput sgr0
sleep 3
menu
