#!/bin/bash
#Configura NETFLIX Experimental
tput setaf 1 ; tput smul ; cat /bin/vercao ; tput sgr0

echo "nameserver 4.2.2.3" > /etc/resolv.conf ; echo "nameserver 4.2.2.4" >> /etc/resolv.conf

apt-get -y install vim dnsutils curl sudo git && \
  curl -sSL https://get.docker.com/ | sh && \
  mkdir -p /opt/netflix-proxy && cd /opt/netflix-proxy && \
  curl -L https://github.com/ab77/netflix-proxy/archive/latest.tar.gz | tar xz --strip-components=1 && \
  ./build.sh

